const GET_APPROVED_SUMMARY_API_ENDPOINT = "/summaries/";
const GET_WRITER_SUMMARY_API_ENDPOINT = "/summaries/writer/me";
export { GET_APPROVED_SUMMARY_API_ENDPOINT, GET_WRITER_SUMMARY_API_ENDPOINT };
