const GET_APPROVED_SUMMARY_API_ENDPOINT = "/summaries/";
const GET_WRITER_SUMMARY_API_ENDPOINT = "/summaries/writer/me";
const SUMMARY_ENDPOINT = "/summaries/";
export {
  SUMMARY_ENDPOINT,
  GET_APPROVED_SUMMARY_API_ENDPOINT,
  GET_WRITER_SUMMARY_API_ENDPOINT,
};
